nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  tag: karpenter-clusterapi-controller
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: { }

affinity: { }

tolerations: [ ]
